### ISSUE TITLE
Build fails on R 4.2.0, linux with RCpp 1.0.8.3

### ISSUE THREAD

**Issue by AshesITR** [eddelbuettel/rprotobuf#89]
I've got a working build on R 4.1.3, but the update to R 4.2.0 caused issues:
The RCpp is version is a freshly installed 1.0.8.3

```
mutators.cpp: In function ‘void rprotobuf::CHECK_messages(const google::protobuf::FieldDescriptor*, SEXP)’:
mutators.cpp:374:13: error: ‘string’ was not declared in this scope; did you mean ‘std::string’?
  374 |             string message = "List element " + s + " is not a message " +
      |             ^~~~~~
      |             std::string
In file included from /usr/include/c++/11.2.0/string:39,
                 from rprotobuf.h:28,
                 from mutators.cpp:19:
/usr/include/c++/11.2.0/bits/stringfwd.h:79:33: note: ‘std::string’ declared here
   79 |   typedef basic_string<char>    string;
      |                                 ^~~~~~
mutators.cpp:376:24: error: ‘message’ was not declared in this scope; did you mean ‘Rcpp::message’?
  376 |             Rcpp::stop(message.c_str());
      |                        ^~~~~~~
      |                        Rcpp::message
In file included from /<lib>/Rcpp/include/Rcpp/api/meat/meat.h:45,
                 from /<lib>/Rcpp/include/Rcpp.h:90,
                 from rprotobuf.h:67,
                 from mutators.cpp:19:
/<lib>/Rcpp/include/Rcpp/api/meat/message.h:26:17: note: ‘Rcpp::message’ declared here
   26 |     inline void message(SEXP s) {
      |                 ^~~~~~~
mutators.cpp: In function ‘void rprotobuf::CHECK_repeated_vals(const google::protobuf::FieldDescriptor*, SEXP, int)’:
mutators.cpp:401:25: error: ‘string’ was not declared in this scope; did you mean ‘std::string’?
  401 |                         string message = "Not a message of type '" +
      |                         ^~~~~~
      |                         std::string
In file included from /usr/include/c++/11.2.0/string:39,
                 from rprotobuf.h:28,
                 from mutators.cpp:19:
/usr/include/c++/11.2.0/bits/stringfwd.h:79:33: note: ‘std::string’ declared here
   79 |   typedef basic_string<char>    string;
      |                                 ^~~~~~
mutators.cpp:403:36: error: ‘message’ was not declared in this scope; did you mean ‘Rcpp::message’?
  403 |                         Rcpp::stop(message.c_str());
      |                                    ^~~~~~~
      |                                    Rcpp::message
In file included from /<lib>/Rcpp/include/Rcpp/api/meat/meat.h:45,
                 from /<lib>/Rcpp/include/Rcpp.h:90,
                 from rprotobuf.h:67,
                 from mutators.cpp:19:
/<lib>/Rcpp/include/Rcpp/api/meat/message.h:26:17: note: ‘Rcpp::message’ declared here
   26 |     inline void message(SEXP s) {
      |                 ^~~~~~~
mutators.cpp: In function ‘void rprotobuf::setNonRepeatedMessageField(google::protobuf::Message*, const google::protobuf::Reflection*, const google::protobuf::FieldDescriptor*, SEXP, int)’:
mutators.cpp:546:23: error: ‘string’ does not name a type; did you mean ‘stdin’?
  546 |                 const string int32str = COPYSTRING(CHAR(STRING_ELT(value, 0)));
      |                       ^~~~~~
      |                       stdin
mutators.cpp:547:80: error: ‘int32str’ was not declared in this scope; did you mean ‘int32_t’?
  547 |                 ref->SetInt32(message, field_desc, Int32FromString<GPB::int32>(int32str));
      |                                                                                ^~~~~~~~
      |                                                                                int32_t
mutators.cpp:556:23: error: ‘string’ does not name a type; did you mean ‘stdin’?
  556 |                 const string uint32str = COPYSTRING(CHAR(STRING_ELT(value, 0)));
      |                       ^~~~~~
      |                       stdin
mutators.cpp:557:82: error: ‘uint32str’ was not declared in this scope; did you mean ‘uint32_t’?
  557 |                 ref->SetUInt32(message, field_desc, Int32FromString<GPB::uint32>(uint32str));
      |                                                                                  ^~~~~~~~~
      |                                                                                  uint32_t
mutators.cpp:572:23: error: ‘string’ does not name a type; did you mean ‘stdin’?
  572 |                 const string int64str = COPYSTRING(CHAR(STRING_ELT(value, 0)));
      |                       ^~~~~~
      |                       stdin
mutators.cpp:573:80: error: ‘int64str’ was not declared in this scope; did you mean ‘int64_t’?
  573 |                 ref->SetInt64(message, field_desc, Int64FromString<GPB::int64>(int64str));
      |                                                                                ^~~~~~~~
      |                                                                                int64_t
mutators.cpp:584:23: error: ‘string’ does not name a type; did you mean ‘stdin’?
  584 |                 const string int64str = COPYSTRING(CHAR(STRING_ELT(value, 0)));
      |                       ^~~~~~
      |                       stdin
mutators.cpp:585:82: error: ‘int64str’ was not declared in this scope; did you mean ‘int64_t’?
  585 |                 ref->SetUInt64(message, field_desc, Int64FromString<GPB::uint64>(int64str));
      |                                                                                  ^~~~~~~~
      |                                                                                  int64_t
make: *** [/usr/lib64/R/etc/Makeconf:177: mutators.o] Error 1
ERROR: compilation failed for package ‘RProtoBuf’
```

**Comment by eddelbuettel** [comment]
Thanks for the heads-up. I have the feeling I just built it recently.   Also, could you clarify which compilers you used?  A `string` vs `std::string` issue is something that can happen when going from one `g++` (or `clang++`) version to another.

**Comment by eddelbuettel** [comment]
FYI it still works at CRAN on all platforms (which is a good leading indicator as CRAN often switches early / pre-release to new compilers for some of these platforms):

![image](https://user-images.githubusercontent.com/673121/166263506-3f6d4f8e-4310-4d84-8a01-45f935a48d99.png)

(via https://cloud.r-project.org/web/checks/check_results_RProtoBuf.html)

**Comment by AshesITR** [comment]
The offending compiler call was:

```
g++ -std=gnu++11 -I"/usr/include/R/" -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto  -I'/<lib>/Rcpp/include' -I/usr/local/include   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto  -c mutators.cpp -o mutators.o
```

```
➜  ~ g++ --version
g++ (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I'm using arch linux and have fully updated.

**Comment by eddelbuettel** [comment]
Can you dig some more at your end?  Could it be a C++ standard library confusion (we sometimes get with `clang`)?  

I just merrily installed on the reference Docker container `r-base` (which I maintain via `rocker/r-base` from which it is copied) using R 4.2.0, g++-11.3.1 and the current CRAN package source and dependencies.  No issues.

**Comment by eddelbuettel** [comment]
It also looks like it is a single line so can you try editing line 374 of `src/mutators.cpp` and make it `std::string` there?

**Comment by AshesITR** [comment]
Happy to dig further, but I'd need a bit more guidance as to what and where to check.

 - I can build all other packages that use Rcpp; it's just this one.
 - `strings /usr/lib/libstdc++.so` reports GLIBCXX_3.4.29 as the maximum GLIBCXX version and GLIBC_2.34 as the maximum GLIBC version
 - `g++ --version` is 11.2.0
 - `R -e packageVersion("Rcpp")` is 1.0.8.3
 - Rcpp installs with `g++ -std=gnu++14 -I"/usr/include/R/" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto  -c rcpp_init.cpp -o rcpp_init.o`
 - RProtoBuf tries to install with `g++ -std=gnu++11 -I"/usr/include/R/" -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto  -I'/<lib>/Rcpp/include' -I/usr/local/include   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto  -c mutators.cpp -o mutators.o`
 - R sessionInfo() reports these things:
```
  > sessionInfo()
  R version 4.2.0 (2022-04-22)
  Platform: x86_64-pc-linux-gnu (64-bit)
  Running under: Arch Linux
  
  Matrix products: default
  BLAS:   /usr/lib/libblas.so.3.10.1
  LAPACK: /usr/lib/liblapack.so.3.10.1
```

**Comment by eddelbuettel** [comment]
I understand pretty much all of the above from the earlier messages (apart from the GLIBC version which is irrelevant as C != C++).  The Rcpp version is also irrelevant.  

I am trying to explain to you that the error appears to be local to your machine.  Meaning you have to look around on your machine why and where.  Also see my previous message on what is likely a one-line fix that should address it.  (And which I can and should also make even if it has so far not bitten anybody else, notably not CRAN, as I demonstrated.)

**Comment by AshesITR** [comment]
The proposed fix (substituting `string` for `std::string` everywhere in the file) causes my local build to succeed.
I have no idea though how to debug the issue that `std::string` isn't visible in the first place.

Using my local version for now. Let me know if you'd like me to submit a (trivial) PR to add the `std::` prefix.

Thanks for your support!

**Comment by eddelbuettel** [comment]
Thanks for confirming.  I am scratching my head a little but one possibility is that maybe 'warnings are errors' or a similar _behavioural_ change at the compiler level _imposed by Arch_ as we do not see it at Ubuntu, Debian, Fedora, ... 

No need for a PR.  I can change that in the file will do so now that you confirmed.

Sorry you had to go through these hoops, it is indeed a bug but it is a little philosophical if we want to blame Arch and `g++` here or the one (arguably sloppy, but nobody was bitten yet in tens of thousands of compilations).  In any event it is an improvement to have it fixed so thanks for your help!

**Comment by eddelbuettel** [comment]
Thanks again for reporting this.  A new release 0.4.19 with the simple fix -- which I presume other distros / builds would have hit eventually too, or maybe it remains local to a settin by Arch.  In any event, the fix was easy, non-controversial and we had other (small) pending changes to good time to cut a release.  Let me know if anything is askew...
